### ISSUE TITLE
Source textures imported with mipmaps are broken when vatlas mipmaps are also enabled

### ISSUE THREAD

**Issue by lewiji** [TamerSoup625/godot-vatlas#1]
First off, I love this addon, just discovered it and it's added a lot of convenience that's been missing from Godot for years especially when it comes to my preferred style of "pixel art in 3D".

In my testing, it seems as though a `VersatileAtlas` will doubly process or else distort the outputted mips, if the input texture has already been imported into godot with mipmaps enabled, and the `VersatileAtlas` also has mipmaps enabled.

Below are some screenshots of a comparison scene I set up to check what was going on when I noticed my lighting acting strangely. There are 4 scenes rendered in separate viewports with their own worlds. All the viewport scenes have the same environment and a directional light set up. A cube mesh extends into the distance with a SpatialMaterial attached. The setup is as follows:

* All 4 scenes have the same VAtlas assigned to albedo texture - these don't change between scenes. So far I've only tested this on normal maps, as it was after setting those up using a VAtlas that I noticed the odd lighting that resulted.
* The top 2 scenes have VAtlas normal maps. The bottom 2 have simple 64x64px StreamTexture normal maps that I cut out of the source spritesheet in GIMP.
* The left column have anisotropic+mipmaps enabled. The right column have only mipmaps enabled (these are enabled in either the VAtlas flags, or in the 64x64 StreamTexture's import settings, respectively).
* The button at the top switches the top row normal map VAtlas `atlas` property between 2 png textures, the first png has aniso+mips enabled in the import settings, the second has only aniso enabled. They're otherwise identical
* all images are using lossless compression in both the import settings and the VAtlas settings.

So, hope that makes sense. The first image has mipmaps+aniso import settings enabled for the normalmap spritesheet png, which is then assigned to the VAtlases in the top 2 scenes:

![image](https://user-images.githubusercontent.com/233380/189164719-f35aec0c-5069-4aa9-b24d-af8387abc37c.png)

The second image uses an identical png but imported with only aniso:

![image](https://user-images.githubusercontent.com/233380/189165586-0bbe7e55-b31a-4e94-a0d5-eef04eb9caf4.png)

As you can see, the "aniso-only normal map png" materials in the second image are nearly indistinguishable between VAtlas and 64x64 png scenes, but the "mips-imported" ones have gone a little strange in the top scenes that use VAtlas for the normal maps. They seem to be causing extreme darkening of the light in the rendered image, which suggests that the mips have been distorted and are giving incorrect normal data as the distance increases and the mip level switches to using the generated smaller mips textures.

I haven't yet investigated the code of the addon, but I suspect that if VAtlas has the mipmaps setting enabled, and the source atlas image has already imported mipmaps, it may be doubling up the processing of the mipmaps, creating invalid results.

**Comment by TamerSoup625** [comment]
I just fixed the issue.
The problem was simply that the Image didn't generate the mipmaps when updating the VAtlas, so the mipmaps themselves were invalid.
Now the image will generate them if the source atlas has mipmaps.

**Comment by lewiji** [comment]
Lightning quick! Thanks for your assistance, I'll download the latest and will enjoy the perfectly mipmapped results :)
