### ISSUE TITLE
With a large atlas image, scrolling/panning the image outside of the bottom panel blocks mouse input to the editor

### ISSUE THREAD

**Issue by lewiji** [TamerSoup625/godot-vatlas#2]
Here's a large atlas image in the bottom panel editor, it's halfway scrolled down so ~400px of the image are "above" the top of the panel.

![image](https://user-images.githubusercontent.com/233380/189196868-8b5c7091-6264-4974-8830-33b9430063d1.png)

This seems to cause blocked input to the editor UI such as the apply/snap settings of the dock itself, as well as any of the code/scene editor that it may overlap.

If I open `bottom_panel.tscn` and change the `Inside`, `TextureRect`, and `SelectedArea` nodes' `mouse_filter` properties to `Ignore`, this fixes the problem and doesn't seem to interfere with the plugin's mouse handling.

**Comment by TamerSoup625** [comment]
Thanks for this issue! Now the bottom panel does not obstruct the input.
I also did some other commits to fix the Input in general, since I first didn't know that _gui_input() existed 😐
